_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  ROI_HEADS:
    NAME: "CascadeROIHeads"
    NUM_CLASSES: 3
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
  ROI_BOX_CASCADE_HEAD:
    IOUS: [0.5, 0.6, 0.7]

DATASETS:
  TRAIN: ("custom_train",)
  TEST: ("custom_val",)

DATALOADER:
  NUM_WORKERS: 2

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  STEPS: (200, 250)
  MAX_ITER: 100
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 100
  WARMUP_METHOD: "linear"
  CHECKPOINT_PERIOD: 100

INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  MASK_FORMAT: "polygon"
  FORMAT: "BGR"

TEST:
  EVAL_PERIOD: 100
  DETECTIONS_PER_IMAGE: 100

OUTPUT_DIR: "./output/custom_dataset"

VERSION: 2
